### ISSUE TITLE
contextify.donlabs.com is broken

### ISSUE THREAD

**Issue by paleozogt** [abeMedia/jquery-contextify#1]
The website referenced on the main github page (http://contextify.donlabs.com) is broken.  It takes me to a page saying "The domain Donlabs.com is listed for sale. Click here to inquire about this domain name."  (See attached image.)

![contextify donlabs com](https://cloud.githubusercontent.com/assets/310894/7923651/2f11ad56-0872-11e5-9f48-9b24fa52919a.png)

**Comment by paleozogt** [comment]
fyi the page over at cdnjs (http://cdnjs.com/libraries/jquery-contextify) also shows this invalid url.

**Comment by abeMedia** [comment]
I'm really sorry but I completely overlooked this. Will update the URLs now...

**Comment by abeMedia** [comment]
Updated the URLs to the new domain: [contextify.js.org](contextify.js.org)
